#!/usr/bin/env bash
# Script linted with https://www.shellcheck.net/
# This is a small helper script to assist in setting the TAURI_SIGNING_PRIVATE_KEY environment variable
# before building Pipali.
#
# This is so you just point this script to your key file, and it will set the variable instead
# of having to cat, copy, and paste the value into an export statement every time.
#
# The Script must be run with either source setupbuild or . ./setupbuild otherwise the environment variable is only set
# in the script's environment.

export TAURI_SIGNING_PRIVATE_KEY;
default_key_file="/home/$USER/.tauri/myapp.key";

# Check if a passed path exists
function fileExists() {
    local file=$1;
    if [ -f "$file" ]; then
        return 0;
    fi
    return 1;
}

# Check if a file is empty
function fileEmpty() {
    local file=$1;
    if [ ! -s "$file" ]; then
        return 0;
    fi
    return 1;
}

# Print a help message
function helpMessage() {
    echo "[setupbuild help]";
    echo "Run this script to automatically set TAURI_SIGNING_PRIVATE_KEY env variable to build Pipali";
    echo "Usage: . ./setupbuild to use default path usually /home/\$USER/.tauri";
    echo "       . ./setupbuild [PATH] to use a key file in a custom path";
    echo "       . ./setupbuild -h or --help to print this help message and exit";
    echo "NOTE: You can also use source to run this script like source setupbuild";
}

# Handle arguments
case "$#" in
    0)
        if fileExists "$default_key_file"; then
            if fileEmpty "$default_key_file"; then
                echo "Error: file at $default_key_file is empty";
                return 1;
            fi
            
            TAURI_SIGNING_PRIVATE_KEY=$(<"$default_key_file");
            return 0;
        else
            echo "Error: $default_key_file not found";
            return 1;
        fi
        ;;
    1)
        file=$1;

        # Print help and exit if help args passed
        if [ "$file" == "-h" ] || [ "$file" == "--help" ]; then
            helpMessage;
            return 0;
        fi

        # Otherwise read args
        if fileExists "$file"; then
            if fileEmpty "$file"; then
                echo "Error: $file is empty";
                return 1;
            fi
            
            TAURI_SIGNING_PRIVATE_KEY=$(<"$file");
            return 0;
        else
            echo "Failed to find key in $file check your path and try again";
            return 1;
        fi
        ;;
    *)
        echo "Invalid args detected!";
        helpMessage;
        return 1;
        ;;
esac